app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('leemon/', include('leemon.urls')),
    path('admin/', admin.site.urls),
]

app/leemon/urls.py
from django.urls import path

from . import views

app_name = 'leemon'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id_cat>/', views.products, name='products'),
    path('basket/', views.basket, name='basket'),
    path('new_user/', views.new_user, name='new_user'),
    path('register_user/', views.register_user, name='register_user'),
    path('save_image/', views.save_image, name='save_image'),
    path('purchase/', views.purchase, name='purchase'),
]

app/leemon/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "category"


class Product(models.Model):
    id_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    value = models.IntegerField(default=0)
    image_url = models.CharField(max_length=200, blank=True)
    id_discount = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "product"


class Image(models.Model):
    url = models.CharField(max_length=200)

    class Meta:
        db_table = "image"


class Customers(models.Model):
    name = models.CharField(max_length=200)
    city = models.CharField(max_length=20)
    email = models.CharField(max_length=100)
    nit = models.CharField(max_length=10)
    card_number = models.CharField(max_length=20)
    card_exp = models.CharField(max_length=10)
    address = models.CharField(max_length=200)
    id_image = models.IntegerField(default=0)
    text_image = models.TextField(default='None')

    def __str__(self):
        return self.name

    class Meta:
        db_table = "customers"


class Purchases(models.Model):
    id_customer = models.ForeignKey(Customers, on_delete=models.CASCADE)
    products = models.TextField() # JSON data
    date = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = "purchases"

app/leemon/views.py
from django.shortcuts import get_list_or_404, render
from django.http import HttpResponse
import json
from leemon import render_pdf
from leemon import save_txt
from leemon import mail

from .models import Category, Product, Customers, Image, Purchases


def index(request):
    category_list = Category.objects.order_by('name')
    context = {'category_list': category_list}

    return render(request, 'leemon/index.html', context)

def products(request, id_cat):
    product_list = get_list_or_404(Product.objects.filter(id_category=id_cat))
    product_dict = {}

    for product in product_list:
        product_data = product.__dict__
        product_data.pop('_state', None)
        product_data['amount'] = 0 # add amount
        product_dict[product.id] = product_data

    product_json = json.dumps(product_dict)

    context = {
        'product_list': product_list,
        'product_json': product_json
    }

    return render(request, 'leemon/products.html', context)

def basket(request):
    return render(request, 'leemon/basket.html')

def new_user(request):
    return render(request, 'leemon/new_user.html')

def register_user(request):
    image_list = Image.objects.all()
    context = {'image_list': image_list}

    if (request.method == "POST"):
        new = Customers()
        new.name = request.POST.get('name')
        new.city = request.POST.get('city')
        new.email = request.POST.get('email')
        new.nit = request.POST.get('nit')
        new.card_number = request.POST.get('card_number')
        new.card_exp = request.POST.get('card_exp')
        new.address = request.POST.get('address')
        new.save()

        id = new.id
        context['id'] = id

    return render(request, 'leemon/register_user.html', context)

def save_image(request):
    context = {}

    if (request.method == "POST"):
        user = Customers.objects.get(id=request.POST.get('id'))
        user.id_image = request.POST.get('image_id')
        user.text_image = request.POST.get('text_image')
        user.save()

        context = {'id': user.id }

    return render(request, 'leemon/purchase.html', context)

def purchase(request):
    details = {}
    if (request.method == "POST"):
        new_purchase = Purchases()
        user = Customers.objects.get(id=request.POST.get('user_id'))
        image = Image.objects.get(id=user.id_image)
        new_purchase.id_customer = user
        new_purchase.products = request.POST.get('products')
        new_purchase.save()

        purchase_id = new_purchase.id
        products = json.loads(new_purchase.products)
        pr = []

        for i in range(len(products) - 1):
            pr.append(products[i])

        total = products[len(products) - 1]

        details = {
            'purchase_id': purchase_id,
            'products': pr,
            'total': total,
            'image_url': image.url,
            'image_text': user.text_image,
            'user_name': user.name,
            'user_nit': user.nit
            }

        txt_path = save_txt.save(user.__dict__)

        pdf_path = render_pdf.render_to_file('leemon/pdf_view.html',
                                             details)
        mail.send(user.email, purchase_id, pdf_path[1], txt_path)

    # return HttpResponse(pdf_path)
    return render(request, 'leemon/confirmation.html', details)

app/leemon/templates/leemon/base.html
{% load static %}
<!doctype html
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Leemon Market</title>
	<!-- Custom styles for this template -->
    <link href="{% static 'assets/dist/css/starter-template.css' %}" rel="stylesheet">
    <!-- Bootstrap core CSS -->
	<link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
    </style>
  </head>
  <body {% block onload %} {% endblock %}>
    <nav class="navbar navbar-expand-md navbar-light fixed-top bg-success">
  <a class="navbar-brand text-white" href="#">Leemon Market</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link text-white" href="{% url 'leemon:index' %}">Catálogo</a>
      </li>
    </ul>
    <a class="nav-link text-white" href="{% url 'leemon:basket' %}">Carrito</a>
  </div>
</nav>

<main role="main" class="container">

  <div class="starter-template">
    {% block body_block %}{% endblock %}
  </div>

</main><!-- /.container -->
<script src="{% static 'assets/dist/js/leemon.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'assets/js/vendor/jquery.slim.min.js' %}"><\/script>')</script>
<script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>
<footer class="container-fluid">
  <p>Footer Text</p>
</footer>

</body>
</html>

app/leemon/templates/leemon/basket.html
{% extends 'leemon/base.html' %}

{% block onload %}onload="render_basket()"{% endblock %}

{% block body_block %}
	<h1>Carrito de compras</h1>
	<div id="basket">	
	</div>
	<a href="{% url 'leemon:new_user' %}">
	<button type="button" class="btn btn-success">Continuar</button>
	</a>
{% endblock %}

app/leemon/templates/leemon/confirmation.html
{% extends 'leemon/base.html' %}
{% load static %}

{% block onload %}onload="clear_session()"{% endblock %}

{% block body_block %}

{% if purchase_id %}
	<h2 class="mb-5">Recibo No: {{ purchase_id }}</h2>
	<p><b>Nombre:</b> {{ user_name }}</p>
	<p><b>Documento:</b> {{ user_nit }}</p>
{% endif %}
	<h3>Detalle</h3>
{% if products %}
	<table class="table mb-5">
	<thead class="thead-dark">
		<tr>
		<th scope="col" class="text-center">Producto</th>
		<th scope="col" class="text-center">Cantidad</th>
		<th scope="col" class="text-center">Sub Total</th>
		</tr>
	</thead>
	<tbody>
		{% for element in products %}
		<tr>
			<td class="text-center">{{ element.name }}</td>
			<td class="text-center">{{ element.amount }} </td>
			<td class="text-center">$ {{ element.total }}</td>
		</tr>
		{% endfor %}
		<tr class="table-secondary">
			<td colspan="2" class="text-center">Total</td>
			<td class="text-center">$ {{ total.sum }}</td>
			</tr>
	</tbody>
	</table>
{% endif %}

<h5>Imagen clave</h5>
{% if image_url %}
	<img class="img-thumbnail" src="{% static 'leemon/' %}{{ image_url }}" style="width: 25%"></br>
	{{ image_text }}
{% endif %}

{% endblock %}

app/leemon/templates/leemon/index.html
{% extends 'leemon/base.html' %}

{% block body_block %}
	<h1>Catálogo de productos</h1>
	<p class="m-5 text-muted">Seleccione una opción</p>

	{% if category_list %}
		<div class="card-columns">
		{% for category in category_list %}
			<div class="card bg-light">
				<div class="card-body text-center">
				  <a href="{% url 'leemon:products' category.id %}"><p class="card-text text-success">{{ category.name }}</p></a>
				</div>
	  		</div>
		{% endfor %}
		</div>	
	{% else %}
		<p>No categories are available.</p>
	{% endif %}

{% endblock %}

app/leemon/templates/leemon/new_user.html
{% extends 'leemon/base.html' %}

{% block body_block %}
<h1 class="mb-5">Crear usuario</h1>

<form action="{% url 'leemon:register_user' %}" method="post">
{% csrf_token %}
<div class="form-group row">
	<label for="name" class="col-sm-2 col-form-label">Nombre completo</label>
	<div class="col-sm-10">
		<input type="text" name="name" id="name" value="" class="form-control">
	</div>
</div>
<div class="form-group row">
	<label for="city" class="col-sm-2 col-form-label">Ciudad</label>
	<div class="col-sm-10">
		<input type="text" name="city" id="city" value="" class="form-control">
	</div>
</div>
<div class="form-group row">
	<label for="email" class="col-sm-2 col-form-label">Email</label>
	<div class="col-sm-10">
		<input type="text" name="email" id="email" value="" class="form-control">
	</div>
</div>
<div class="form-group row">
	<label for="ni" class="col-sm-2 col-form-label">Número de documento</label>
	<div class="col-sm-10">
		<input type="text" name="nit" id="nit" value="" class="form-control">
	</div>
</div>
<div class="form-group row">
	<label for="card_number" class="col-sm-2 col-form-label">Número de tarjeta</label>
	<div class="col-sm-10">
		<input type="text" name="card_number" id="card_number" value="" class="form-control">
	</div>
</div>
<div class="form-group row">
	<label for="card_exp" class="col-sm-2 col-form-label">Fecha de vencimiento</label>
	<div class="col-sm-10">
		<input type="text" name="card_exp" id="card_exp" value="" class="form-control">
	</div>
</div>
<div class="form-group row">
	<label for="address" class="col-sm-2 col-form-label">Dirección</label>
	<div class="col-sm-10">
		<input type="text" name="address" id="address" value="" class="form-control">
	</div>
</div>

<div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-success">Crear usuario</button>
    </div>
</div>

</form>
{% endblock %}

app/leemon/templates/leemon/pdf_view.html
{% load static %}
<!doctype html
<html lang="es">
<head>
<title>Recibo de compra {{ purchase_id }}</title>
<style>
table, th, td {
	border: 1px solid black;
	text-align: center;
}
</style>
<body>

{% if purchase_id %}
	<h2 style="text-align: center">Recibo No: {{ purchase_id }}</h2>
	<p><b>Nombre:</b> {{ user_name }}</p>
	<p><b>Documento:</b> {{ user_nit }}</p>
{% endif %}
	<h3 style="text-align: center">Detalle</h3>
{% if products %}
	<table style="width: 100%;">
	<thead>
		<tr>
		<th>Producto</th>
		<th>Cantidad</th>
		<th>Sub Total</th>
		</tr>
	</thead>
	<tbody>
		{% for element in products %}
		<tr>
			<td>{{ element.name }}</td>
			<td>{{ element.amount }} </td>
			<td>$ {{ element.total }}</td>
		</tr>
		{% endfor %}
		<tr>
			<td colspan="2">Total</td>
			<td>$ {{ total.sum }}</td>
		</tr>
	</tbody>
	</table>
{% endif %}
</br>
<h4>Imagen clave</h4>
{% if image_url %}
	<img class="img-thumbnail" src="{% static 'leemon/' %}{{ image_url }}" style="width: 100px;"></br>
	{{ image_text }}
{% endif %}

</body>
</head>
</html>

app/leemon/templates/leemon/products.html
{% extends 'leemon/base.html' %}
{% load static %}

{% block body_block %}

	{% if product_list %}
		<div class="card-deck">
		{% for product in product_list%}
			<div class="card bg-light">
				<img class="card-img-top" src="{% static 'leemon/' %}{{ product.image_url }}" alt="Card image">
				<div class="card-body text-center">
					<h4 class="card-title">{{ product.name }}</h4>
						<p class="card-text text-black-50 h3 m-5">$ {{ product.value }}</p>
						{% if product.id_discount != 0 %}
							<p class="card-text badge text-wrap bg-warning"><b>Descuento</b></br>
								{% if product.id_discount == 1 %}
									El segundo al 50%
								{% endif %}
								{% if product.id_discount == 2 %}
									Pague 2 lleve 3
								{% endif %}
							</p>
						{% endif %}
						<p class="card-text">{{ product.description }}</p>
						<div class="form-group">
								<input class="form-control mt-3 mb-3" type="text" placeholder="Ingrese cantidad..." 
									id="amount_tmp-{{ product.id }}" 
									name="amount_tmp-{{ product.id }}"
									onchange="calc_total({{ product.id }}, {{ product.value }}, {{ product.id_discount }}, this)"
									onkeyup="calc_total({{ product.id }}, {{ product.value }}, {{ product.id_discount }}, this)">
								<input type="hidden"
									id="amount-{{ product.id }}" 
									name="amount-{{ product.id }}">

								<button class="btn btn-success" type="button" 
									onclick="add_product('{{ product.id }}', 'add')">
									Agregar
								</button>
								<button class="btn btn-secondary" type="button" 
									onclick="add_product('{{ product.id }}', 'quit')">
									Quitar
								</button>
						</div>
						<p>
							Cantidad: <span id="amount-div{{ product.id }}"></span></br>
							Total: <span id="total-{{ product.id }}"></span></br>
							<input type="hidden"
								id="totalForm-{{ product.id }}" 
								name="totalForm-{{ product.id }}">
						</p>
				</div>
			</div>
		{% endfor %}
		</div>
	
	{% else %}
		<p>No products are available.</p>
	{% endif %}

	<script>
	let products = {};

	if (sessionStorage.basket) {
			products_obj = JSON.parse(sessionStorage.basket);
			products_more = {{ product_json|safe }};
			products = Object.assign(products_obj, products_more);
		}
	else {
		{% if product_json %}
			products = {{ product_json|safe }};
		{% endif%}
	}
	</script>

{% endblock %}

app/leemon/templates/leemon/purchase.html
{% extends 'leemon/base.html' %}

{% block onload %}onload="load_products()"{% endblock %}

{% block body_block %}
{% if id %}
	<div class="card">
		<div class="card-body text-center">
			<form action="{% url 'leemon:purchase' %}" method="post">
			{% csrf_token %}
			<input type="hidden" name="user_id" id="user_id" value="{{ id }}">
			<input type="hidden" name="products" id="products" value="">
			<p class="h5 m-5">Todo está listo</p>
			<button type="submit" class="btn btn-success">Pagar</button>
			</form>
		</div>
	</div>
{% endif %}

{% endblock %}

app/leemon/templates/leemon/register_user.html
{% extends 'leemon/base.html' %}
{% load static %}

{% block body_block %}

{% if id and image_list %}
	<p>Selecciona una imágen personalizada</p>
	<form action="{% url 'leemon:save_image' %}" method="post">
	{% csrf_token %}
	<div class="form-check">
		<div class="card-columns">
		{% for image in image_list %}
			<div class="card bg-light">
				<img class="card-img-top" src="{% static 'leemon/' %}{{ image.url }}" alt="Card image">
				<div class="card-body text-center">
					<input type="radio" 
						id="{{ image.id }}" 
						name="image_id" 
						value="{{ image.id }}"
						class="form-check-input">
					<label for="{{ image.id }}" class="form-check-label card-text">{{ image.url }}</label>
				</div>
			</div>
		{% endfor %}
		</div>
	</div>
	<div class="m-5">
		<label for="text_image">Escribe un texto que describa la imágen</label>
		<input type="text" name="text_image" id="text_image" value="" class="form-control">
		<input type="hidden" name="id" id="id" value="{{ id }}">
		<button type="submit" class="btn btn-success m-5">Guardar</button>
	</div>
	</form>
{% else %}
    <p>No user data was record.</p>
{% endif %}

{% endblock %}